### ISSUE TITLE
Recipes not registered in JEI and unable to edit in CraftTweaker/KubeJS

### ISSUE THREAD

**Issue by Jarva** [Hidoni/CustomizableElytra#11]
Recipes related to dying and applying banners don't seem to be registered properly and so they don't show up in JEI and can't be adjusted or changed in CraftTweaker or KubeJS.

I planned to change the result of the dye recipes to be the equivalent banner base as it gives bright colours, but this isn't possible currently.

**Comment by Hidoni** [comment]
Hey, I don't think this is a bug as much as it is a limit with the way CraftTweaker/KubeJS work.
The crafting recipes are implemented through Minecraft's special crafting recipe system, which gives completely custom behavior for the input and output, and is required because NBT data is being modified. For dying, this works identically to the way it does for leather armor in vanilla and for applying banners, it works the same way that it does with shields.
Correct me if I'm wrong here, but I don't believe those kinds of recipes can be modified in CraftTweaker/KubeJS and they don't show up in JEI.

**Comment by Jarva** [comment]
I just dived into it a little further and it's possible to edit custom recipe types with KubeJS but it seems customizable elytra recipes are registered without any input or output items and it's all handled under the hood, this makes it impossible to tweak properly as there's just the one recipe for all operations, instead of a recipe per operation. Not sure if this is an easy solve, otherwise I can fork the repo to change the recipes and distribute the fork in my modpack.

**Comment by Hidoni** [comment]
Yeah, I think you'll have to fork and make that change yourself. I'm not aware of a vanilla system where the recipe can be static, as it dynamically changes based on the content of the crafting grid (Mixing different dyes together or copying banner patterns over, etc)
