### ISSUE TITLE
Cape still visible with Wavey Capes installed, elytra uncoloured.

### ISSUE THREAD

**Issue by Inqie** [Hidoni/CustomizableElytra#15]
When Wavey Capes (Forge) is installed, customized elytra is grayscale instead of matching colour to cape. The cape also does not disappear when customized elytra is equipped. This happens with both the chest slot and the Curios back slot.

Expected behaviour, of course, is that the cape should disappear when any elytra is equipped in any slot, and the elytra should take on the colours of the cape.

**System Info:**
Minecraft Version: 1.16.5
Forge Version: 36.2.9
Customizable Elytra Version: 1.5.7
Wavey Capes Version: 1.0.4
Curious Elytra Version: 4.0.2.3
Curios Version: 4.0.5.3
Java Version: 1.8.0_242 64bit
CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics
GPU: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2

**Comment by Hidoni** [comment]
Hey, thanks for reporting! :)
The grayscale effect is part of the logic for letting you use the cape patterns with your colors on it, however it also gets applied when the elytra has no dye/banner, thus making your elytra pattern grayscale instead of matching the cape, if you want the vanilla behavior, you can turn your elytra back into the vanilla one using a crafting table!

The issue with Wavey Capes seems more easily fixable on their side, as the logic dictating hiding the cape on their end is [hard-coded to only work with the vanilla elytra](https://github.com/tr7zw/WaveyCapes/blob/1.16/WCShared/src/main/java/dev/tr7zw/waveycapes/renderlayers/CustomCapeRenderLayer.java#L42), and since it's from a mod, I don't believe I can use a mixin to fix it like in vanilla.
If the mod is updated to support other items hiding the cape I'll gladly do what's needed to fix it on my side!

**Comment by Hidoni** [comment]
I realized that the grayscale cape texture is less than ideal, so I've fixed that in the newest version (1.6.1). :)

**Comment by JesseStrijker** [comment]
Hi, is the grayscale also fixed for 1.17? because it doesnt seem fixed there

**Comment by Hidoni** [comment]
It is. Definitely worked for me in 1.6.2, but the fix was pushed in 1.6.1 so it should work for you too.

**Comment by Hidoni** [comment]
Fixed in version 2.0.0 of Customizable Elytra
