### ISSUE TITLE
Banner elytras fail to render with 3d Skin Layers and Iris

### ISSUE THREAD

**Issue by ghost** [Hidoni/CustomizableElytra#31]
Elytras with banners seem to render the base and all patterns as white, making the banner appear as a white empty one. This however only happens when both 3d Skin Layers and Iris are loaded, and the banner renders fine if either mod is absent.
I'm not expecting this to be a very important issue though as removing either mod fixes it.

Game version and mod list:
- Minecraft 1.20.1
- Fabric Loader 0.14.22
- Fabric API 0.87.0+1.20.1
- Customizable Elytra 2.1.0+1.20
- 3d Skin Layers 1.5.4-mc1.20.1
- Iris 1.6.8
- Sodium 0.5.2* (required by Iris)
- Indium 1.0.25+mc1.20.1* (added for Sodium/Fabric Rendering API compat.)

\* Note that Sodium and Indium were always present in my testing, even when Iris was not.

How the elytra looks like with either mod installed (but not both)
![image](https://github.com/Hidoni/CustomizableElytra/assets/25990664/d0e37f70-6fbc-491a-809f-5a27fc35f8dd)

How the elytra looks like with both mods installed
![image](https://github.com/Hidoni/CustomizableElytra/assets/25990664/94980228-d891-4c60-86d4-f291634f2e82)

**Comment by Hidoni** [comment]
I'm not the most well versed with rendering, but from what I've gathered, it seems like the issue stems from the way Iris optimizes rendering. Rendering the banner patterns on the elytra relies on several layers (enchantment glint, base pattern and then banner patterns) being rendered in an exact order, and it looks like Iris messes with that.  
This only shows up once 3d skin layers is installed because that mod adds in more things that are rendered on the player model, which I presume is what triggers these optimizations in Iris.  
I managed to find a workaround for it by simply making the elytra layer be the last one rendered, no matter what, but that feels like a hacky (and probably not perfect) fix for an issue that could potentially be fixed on Iris' end, so for now I would prefer to keep this issue open and suggest that you open an issue on their repo and see if it's possible for it to be fixed there ^^

**Comment by CleverBalloon** [comment]
I'm having the same issue, the banner renders on my player model in my inventory but doesn't actually render in the world.

**Comment by Smockinssnim** [comment]
Hello is there a way to fix this im having the same problem.
The game will show me vanilla elytras but in the 3d skin llayer menu they will be displayed as customized with the banner/trim i used on them.

**Comment by Apollonu** [comment]
Turning on Compatibility Mode in 3D Skin Layers seems to fix this issue @Hidoni 
![image](https://github.com/user-attachments/assets/02bd40a6-75c7-480f-ba17-c061bc14101c)
One with paper
![image](https://github.com/user-attachments/assets/d61abe08-67f8-42b7-921f-806736280d3b)

**Comment by ghost** [comment]
Thanks, just tested it and it does work.
